workspace:
  base: /go
  path: src/github.com/uzuna/learn-go-binary-parse

pipeline:
  go:
    image: golang:1.8
    commands:
      - go build
      # - go test ./...
      - go test -cover ./model/zip/